export default [
   { "label": "Android"       , "value": "Android"       }  , 
   { "label": "C"             , "value": "C"             }  , 
   { "label": "C#"            , "value": "C#"            }  , 
   { "label": "C++"           , "value": "C++"           }  , 
   { "label": "CSS"           , "value": "CSS"           }  , 
   { "label": "Django"        , "value": "Django"        }  , 
   { "label": "Flask"         , "value": "Flask"         }  , 
   { "label": "Go"            , "value": "Go"            }  , 
   { "label": "HTML"          , "value": "HTML"          }  , 
   { "label": "Java"          , "value": "Java"          }  , 
   { "label": "Javascript"    , "value": "Javascript"    }  , 
   { "label": "JSON"          , "value": "JSON"          }  , 
   { "label": "Lua"           , "value": "Lua"           }  , 
   { "label": "NodeJS"        , "value": "NodeJS"        }  , 
   { "label": ".NET"          , "value": ".NET"          }  , 
   { "label": "Objective-C"   , "value": "Objective-C"   }  , 
   { "label": "Perl"          , "value": "Perl"          }  , 
   { "label": "PHP"           , "value": "PHP"           }  , 
   { "label": "Python"        , "value": "Python"        }  , 
   { "label": "ReactJS"       , "value": "ReactJS"       }  , 
   { "label": "Ruby"          , "value": "Ruby"          }  , 
   { "label": "Ruby on Rails" , "value": "Ruby on Rails" }  , 
   { "label": "Rust"          , "value": "Rust"          }  , 
   { "label": "Scala"         , "value": "Scala"         }  , 
   { "label": "SQL"           , "value": "SQL"           }  , 
   { "label": "Swift"         , "value": "Swift"         }  , 
   { "label": "XML"           , "value": "XML"           }  , 
];
