import React from "react";

import Header from "components/2020/Header";
import Footer from "components/2020/Footer";

export default { title: "Layout" };

export const Grid = () => (
  <div className="layout">
    <Header />
    <div className="layout__content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget vulputate nibh. Donec congue sodales blandit. Aliquam suscipit massa ut justo gravida, vitae tristique neque iaculis. Proin luctus eget lacus in pharetra. Integer ullamcorper non nunc et euismod. Ut efficitur laoreet velit varius ornare. Nunc a dolor consectetur, accumsan tortor vitae, consequat quam. Phasellus maximus, lectus sed fermentum porta, odio magna interdum metus, commodo tempor metus est at purus. Mauris quis risus quis libero placerat cursus. Aenean non eleifend ipsum. Nullam volutpat odio sit amet elit pulvinar, eget volutpat ipsum porttitor. Nam accumsan nibh in elit pharetra pharetra. Nullam sit amet efficitur nibh. Nulla aliquam vitae felis malesuada commodo.</p>

      <p>Morbi quam lectus, dapibus ut risus a, condimentum porta ante. Nullam nisi felis, luctus ac tincidunt sed, laoreet a risus. Duis sed consectetur lectus, a laoreet lectus. Nam aliquam sem sed ipsum vestibulum, sit amet venenatis leo efficitur. Morbi maximus risus sit amet magna facilisis laoreet. In non metus non tortor tempor sagittis. Ut eleifend orci vel enim molestie, a rhoncus est blandit. Nunc facilisis augue eu iaculis egestas. Phasellus ac ex commodo mauris bibendum commodo. Quisque id diam maximus, pharetra erat sed, laoreet risus.</p>

      <p>Suspendisse condimentum suscipit ex, nec laoreet nisi imperdiet ut. Nullam euismod sem eu congue ultricies. Fusce viverra mauris tortor, quis rutrum purus consectetur eu. Praesent sed odio in risus lobortis lacinia a id erat. Nulla lacinia erat vel dui blandit, ut sollicitudin magna porta. Pellentesque sodales, velit vel pellentesque finibus, sem lacus molestie lorem, sit amet blandit tortor eros sodales nibh. Maecenas elit erat, viverra in leo et, gravida efficitur metus. Nunc tincidunt velit non scelerisque aliquet. Maecenas rhoncus lacus quis fringilla pellentesque. Fusce eget tincidunt justo. Phasellus et dui pretium, aliquet lectus vitae, elementum nulla.</p>

      <p>Nullam aliquam nisi quis sapien imperdiet eleifend. Mauris quis fermentum metus. Sed eget tempus nisl. Mauris posuere nulla in lorem scelerisque, venenatis laoreet arcu dignissim. Sed in elit turpis. Quisque lacinia quam neque, vitae semper libero dictum ut. Vivamus rhoncus interdum enim in hendrerit. Fusce hendrerit ex sed gravida volutpat. Praesent porttitor orci hendrerit gravida volutpat. Fusce hendrerit viverra mollis. Aliquam porta, nisl vel venenatis pellentesque, enim arcu placerat felis, vitae tempor nisi lectus et tortor. Phasellus porta est at dui consectetur, ac tristique nisi dictum.</p>

      <p>Aliquam sollicitudin at ipsum quis dictum. Donec semper nibh id est placerat, non interdum risus dictum. Sed nisi lectus, tincidunt quis pharetra ac, tempor in neque. Pellentesque nec consectetur dolor. Donec aliquam euismod sapien, at auctor quam bibendum a. Mauris suscipit pellentesque feugiat. Maecenas euismod, ante eget lacinia suscipit, ligula mauris feugiat arcu, eu sagittis velit ligula et lectus.</p>

      <p>Curabitur quis metus vitae ante finibus sollicitudin eu quis ex. Sed semper dui eget elementum eleifend. Suspendisse at suscipit risus, quis commodo dolor. Aliquam sed sem sodales, auctor nulla vel, finibus orci. Suspendisse sit amet mi ac risus fermentum consectetur et eu enim. Sed quis euismod ipsum, in sodales nisi. Sed eget imperdiet risus. Nunc hendrerit neque id purus malesuada, quis faucibus urna tincidunt. Nulla facilisi. Phasellus non tellus fermentum eros dictum dapibus. Ut ornare ipsum eu lacus euismod, consequat ultricies risus egestas. Pellentesque pulvinar pulvinar dui ac vulputate. Integer vitae sodales mi, eu ultricies lectus. Vestibulum sed turpis at tellus tristique ornare eu non nibh. Vestibulum molestie quis orci ut vehicula. Cras eget orci non tortor hendrerit scelerisque mollis vel ex.</p>

      <p>In fringilla sagittis eros sed varius. Curabitur pharetra aliquam ipsum, vitae interdum magna scelerisque sed. In aliquet nisl quis sem consectetur, eget ornare arcu bibendum. Maecenas ac velit tempor, ultrices lorem et, ultricies ex. Sed pulvinar orci vulputate posuere ornare. Etiam ullamcorper euismod sapien iaculis facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

      <p>Suspendisse potenti. Nam semper mattis urna a tristique. Proin sit amet est sapien. Phasellus vitae tincidunt nunc, scelerisque iaculis nibh. Donec euismod ultrices sodales. Integer eu sem imperdiet, luctus tortor faucibus, egestas leo. Quisque maximus est sapien, eget accumsan risus convallis id. Nunc leo velit, rhoncus in cursus vel, ultricies sit amet erat. Proin quis elit dignissim, efficitur eros sit amet, lobortis neque. Quisque porttitor, nunc at venenatis convallis, libero velit venenatis est, ut congue leo lorem eget elit. Sed maximus porta libero vel porttitor.</p>

      <p>Sed semper eleifend nisi in consectetur. Suspendisse vel tortor laoreet, imperdiet orci non, commodo metus. Cras id ante lacinia, mattis augue id, ultricies orci. Fusce condimentum nisi a fermentum accumsan. Aliquam congue luctus lorem, eu consectetur mi consequat non. In luctus metus nec tellus fringilla, quis aliquet elit ornare. Suspendisse gravida risus et suscipit fermentum. Integer bibendum ac erat ac venenatis. Sed convallis mollis est. Mauris vitae aliquet sapien. Phasellus interdum, sem ut molestie pharetra, mauris eros scelerisque nibh, sit amet tincidunt metus neque eget nisl. Ut porttitor eget nisi et luctus. Sed consectetur, enim luctus consectetur pharetra, quam sapien posuere urna, in vestibulum massa nunc at quam. Morbi auctor nibh at urna cursus ultricies. Vivamus eget libero turpis.</p>

      <p>Etiam fringilla pretium accumsan. Phasellus malesuada mollis gravida. Donec convallis, enim eget viverra lacinia, neque ante porttitor sem, maximus sollicitudin lorem orci vel tortor. Suspendisse tempor ligula non tempus varius. Aliquam erat volutpat. Integer in sem non elit interdum imperdiet eget at urna. Sed vitae ex placerat est ullamcorper aliquet at eget dui. Nam tincidunt felis ut lectus tincidunt consequat. Integer porttitor accumsan congue. Maecenas auctor, justo ullamcorper ullamcorper pulvinar, metus velit imperdiet libero, sed rhoncus eros velit suscipit turpis. Cras quis dolor urna. Proin pellentesque, urna a dapibus eleifend, velit mauris pellentesque augue, et laoreet quam sapien vel elit. Phasellus elementum, ex nec suscipit dapibus, ante urna luctus lorem, sit amet vestibulum nibh risus sed massa. Donec iaculis velit ultrices, scelerisque ante id, cursus neque.</p>
    </div>
    <Footer />
  </div>
);
